### ISSUE TITLE
QSplitter vs. QMainWindow::seperator

### ISSUE THREAD

**Issue by Entitale** [ArtemisGraphic/MTGO-Theme-for-Cockatrice#1]
The theme was missing some visual dividers between different QDockWidgets in the style.css file.

`QMainWindow::separator:vertical {
   border-left: 1px solid #ebc77c;
   border-right: 1px solid #ebc77c;
   width: 4px;
   height: 4px;
   image: url(img/splitter-vertical-handle.png);
}
QMainWindow::separator:horizontal {
   border-top: 1px solid #ebc77c;
   border-bottom: 1px solid #ebc77c;
   width: 4px;
   height: 4px;
   image: url(img/splitter-horizontal-handle.png);
}`

**Comment by ArtemisGraphic** [comment]
Rules added to CSS
